### ISSUE TITLE
How to handle files which don't have digital codes

### ISSUE THREAD

**Issue by yuumii-san** [SmithLabNeuro/nevutils#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A description of what you want to happen.

**Describe alternatives you've considered**
A description of any alternative solutions or features you've considered.

**Additional context**

**Comment by mattslab** [comment]
@deepaissar 
Pushed a modified concatenateNevFiles. This function fails on files like Sa230317 (s621) because the 0001 file from that session has no trial start or end markers. We need to think of how to handle those cases.

**Comment by deepaissar** [comment]
Added a fix in nev2dat to return an empty dat plus warning when given an nev file with no trial starts (i.e. you started and stopped the file before the subject did a complete trial). Tested w/ Sa230317_0001 and it works.

**Comment by deepaissar** [comment]
Added a fix in nev2dat to return an empty dat plus warning when given an nev file with no trial starts (i.e. you started and stopped the file before the subject did a complete trial). Tested w/ Sa230317_0001 and it works.
