### ISSUE TITLE
Add a new cmp2map.m code

### ISSUE THREAD

**Issue by yuumii-san** [SmithLabNeuro/nevutils#6]
**Is your feature request related to a problem? Please describe.**
I believe Matt updated cmp2map.m to fix the errors but I could not find the code on github. Could we add the code with the problem description and how fixed it?
 (I don't know which repository is the right one to use for this so this does not have to be under nevutils)

**Describe the solution you'd like**
Add the new code with some description to keep the records

**Describe alternatives you've considered**
Adding it to another repository would be fine too as long as it will be somewhere within SmithLabNeuro

**Additional context**
We could not load cmp files for Pumbba and Wakko's new arrays. To solve this issue, Matt updated the code in Dec 2023.

**Comment by yuumii-san** [comment]
I assigned people who, I believe, involved in this update

**Comment by meganmcd13** [comment]
This code is in the "labcode" repo rather than nevutils.

**Comment by mattslab** [comment]
Yes - that's in "labcode". I don't think it has to be that way, I could see readcmp being in nevutils. But cmp2map is really a "rig utility" and not useful other than the rig. My notion is that labcode should contain the key utilities / functions we need for the lab, and "nevutils" is slightly more external-facing, and has more general purpose stuff to share with other labs using Ripple (especially with Ex). But I'm open to changes if needed.

**Comment by yuumii-san** [comment]
I thought that "labcode" is not an active repository so it was not on my radar. But that makes sense, Matt.

**Comment by mattslab** [comment]
Sorry, I should have been more clear. I think we should keep using "labcode" for some of our shared code that is not NEV-specific. For example, "copyToRaptor" lives there. We can talk in a future meeting about what else to put there.
